version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosec
    - ineffassign
    - unused
    - misspell
    - unconvert
    - prealloc
  disable:
    - depguard
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec
      - path: test/
        linters:
          - errcheck
          - gosec
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: false
    gosec:
      excludes:
        - G104
    govet:
      enable-all: true
      disable:
        - fieldalignment
    misspell:
      locale: US

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/dapr/dapr-mcp-server
